apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
    name: {{ include "hygea-stack.fullname" . }}-db
    namespace: {{ .Release.Namespace }}
spec:
    instances: 2

    storage:
        size: 1Gi

    monitoring:
        enablePodMonitor: true